version: "3.9"

services:

  relay-1:
    container_name: relay-1
    build:
      context: .
      dockerfile: Dockerfile
    image: relay-app
    restart: unless-stopped
    environment:
    - BOND_NAME=${BOND_NAME}
    - PACT_PRIVATE_KEY=${PACT_PRIVATE_KEY}
    - INFURA_API_TOKEN
    - LOG_LEVEL

  relay-2:
    container_name: relay-2
    build:
      context: .
      dockerfile: Dockerfile
    image: relay-app
    restart: unless-stopped
    environment:
    - BOND_NAME=${BOND_NAME_2}
    - PACT_PRIVATE_KEY=${PACT_PRIVATE_KEY_2}
    - INFURA_API_TOKEN
    - LOG_LEVEL

  lockup:
    container_name: lockup
    build:
      context: .
      dockerfile: test/Dockerfile
    image: relay-test-lockup
    restart: unless-stopped
    environment:
    - INFURA_API_TOKEN
    - ETH_TEST_PRIVATE_KEY
    - LOG_LEVEL
